name: iqran
description: A personal Quran app for murajaah
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.0
  sqflite: ^2.3.3
  path: ^1.9.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.38
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  flutter_compass: ^0.8.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  uuid: ^4.0.0
  lottie: ^3.1.0
  showcaseview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # SPLASH SCREEN
  flutter_native_splash: ^2.4.0

  # APP ICON
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/images/onboarding/
    - assets/data/

  fonts:
    - family: QuranFont
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

# ======================
# SPLASH CONFIG
# ======================
flutter_native_splash:
  color: "#0F0B1F"
  image: assets/images/splash.png

  android: true
  ios: false
  web: false

  android_12:
    image: assets/images/splash.png
    color: "#0F0B1F"

# ======================
# APP ICON CONFIG
# ======================
flutter_icons:
  android: true
  ios: false
  image_path: assets/images/logo.png
